// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
///
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA54EngXTwEM_-3P-9yaN_tMd6fM5c8kuw',
    appId: '1:11564624912:web:0c110aa2cb8f078c606e95',
    messagingSenderId: '11564624912',
    projectId: 'proyectopm2-e3c34',
    authDomain: 'proyectopm2-e3c34.firebaseapp.com',
    storageBucket: 'proyectopm2-e3c34.firebasestorage.app',
    measurementId: 'G-F3S4STN68G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt_ZutWBVszpl4jepQ4ziHDZANSd67ca8',
    appId: '1:11564624912:android:75b373f33856c72c606e95',
    messagingSenderId: '11564624912',
    projectId: 'proyectopm2-e3c34',
    storageBucket: 'proyectopm2-e3c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbMC4bn28UZ2LQ4YkEYGzCKU3tWItPfE',
    appId: '1:11564624912:ios:32ae3c17eb8aea17606e95',
    messagingSenderId: '11564624912',
    projectId: 'proyectopm2-e3c34',
    storageBucket: 'proyectopm2-e3c34.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbMC4bn28UZ2LQ4YkEYGzCKU3tWItPfE',
    appId: '1:11564624912:ios:32ae3c17eb8aea17606e95',
    messagingSenderId: '11564624912',
    projectId: 'proyectopm2-e3c34',
    storageBucket: 'proyectopm2-e3c34.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA54EngXTwEM_-3P-9yaN_tMd6fM5c8kuw',
    appId: '1:11564624912:web:34d2876f8dce8e79606e95',
    messagingSenderId: '11564624912',
    projectId: 'proyectopm2-e3c34',
    authDomain: 'proyectopm2-e3c34.firebaseapp.com',
    storageBucket: 'proyectopm2-e3c34.firebasestorage.app',
    measurementId: 'G-BHDYBKNFT8',
  );
}
